### ISSUE TITLE
Exception when integrating Parallax.inside into a Dismissible

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [letsar/flutter_parallax#3]
```
I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter: The following assertion was thrown during performLayout():
I/flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize
I/flutter: || debugDoingThisLayout ||
I/flutter:                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not
I/flutter:                  true.
I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter: more information in this error message to help you determine and fix the underlying cause.
I/flutter: In either case, please report this assertion by filing a bug on GitHub:
I/flutter:   https://github.com/flutter/flutter/issues/new
I/flutter: When the exception was thrown, this was the stack:
I/flutter: #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart)
I/flutter: #3      RenderBox.size (package:flutter/src/rendering/box.dart:1463:6)
I/flutter: #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2377:24)
I/flutter: #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2109:24)
I/flutter: #6      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:1981:39)
I/flutter: #7      ParallaxInsideDelegate.getChildScrollRatio (package:flutter_parallax/src/rendering/parallax.dart:231:49)
I/flutter: #8      ParallaxWithAxisDirectionDelegate.getPositionForChild (package:flutter_parallax/src/rendering/parallax.dart:148:28)
I/flutter: #9      RenderParallaxSingleChildLayoutBox.performLayout (package:flutter_parallax/src/rendering/parallax.dart:340:41)
I/flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
I/flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter: #12     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
I/flutter: #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
I/flutter: #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
I/flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter: #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
I/flutter: #21     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter: #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
I/flutter: #23     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter: #24     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1451:7)
I/flutter: #25     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:710:18)
I/flutter: #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter: #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter: #32     _invoke (dart:ui/hooks.dart:120:13)
I/flutter: #33     _drawFrame (dart:ui/hooks.dart:109:3)
```

**Comment by creativecreatorormaybenot** [comment]
I have come across more issues like that, finding myself unable to size and seeing the `performLayout()` a lot. I wrote some workaround for me, but it is not a solution I could pull request.

**Comment by letsar** [comment]
Hi @creativecreatorormaybenot, can you post the minimal code sample to reproduce this issue?

**Comment by creativecreatorormaybenot** [comment]
I found out that the actual issue is actually just the integration into a `Dismissible` widget, which makes the code sample very short:

```
import 'package:flutter/material.dart';
import 'package:flutter_parallax/flutter_parallax.dart';

main() => runApp(MaterialApp(
    home: Scaffold(
        body: ListView.builder(
            itemBuilder: (_, __) => Dismissible(
                key: UniqueKey(),
                child: Parallax.inside(
                    mainAxisExtent: 150.0,
                    child: Image.network(
                        'http://image.flaticon.com/icons/png/512/2/2010.png')))))));
```

Apart from this lookin really "interesting", you will encounter the exception I described above each time you scroll vertically.
