### ISSUE TITLE
The method '-' was called on null.

### ISSUE THREAD

**Issue by aarajput** [letsar/flutter_parallax#9]
I am getting this exception.

**Comment by aarajput** [comment]
Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at /Users/ali/Tools/flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

**Comment by elertan** [comment]
Same here
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)

The relevant error-causing widget was: 
  Parallax file://.../MyWidget.dart:64:31
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
...
The following RenderObject was being processed when the exception was fired: RenderParallaxSingleChildLayoutBox#09b2f relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
```

Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-NL)

**Comment by MrAbdul** [comment]
same here:

`The method '-' was called on null.
Receiver: null
Tried calling: -(291.2934396619042)
The relevant error-causing widget was
    Parallax `

its still functioning correctly, but I am worried if that exception is going to cause errors down the line?

**Comment by woutervanwijk** [comment]
Here also:

════════ Exception caught by rendering library ═════════════════════════════════
The method '-' was called on null.
Receiver: null
Tried calling: -(4040.780099161113)
The relevant error-causing widget was
    Parallax

**Comment by crushman1** [comment]
me to...

**Comment by pnemonic78** [comment]
+1

**Comment by alex-thmv** [comment]
Same problem
